spring.application.name=Tjabal
server.servlet.context-path=/tjabal

spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:mariadb://localhost:3306/tjabal
spring.datasource.username=tjabal
spring.datasource.password=Tj@b@l12!12!
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.show-sql: true

logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR